---
# This role installs some useful tools for admins and devs

- name: removing vim-tiny
  become: true
  apt:
    name: vim-tiny
    state: absent

- name: installing tools
  become: true
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    name: "{{ item }}"
  loop:
    - vim
    - mc
    - curl
    - unzip
    - htop
    - yamllint
    - ansible-lint
...
