---
# This role installs the lamp stack

- name: install apache
  become: true
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    name: apache2

- name: allow apache full and openssh
  become: true
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "{{ http_port }}"
    - "{{ https_port }}"
    - "{{ ssh_port }}"

...
