---
# This role installs aptitude, which is preferred by Ansible to the apt

- name: installing aptitude
  become: true
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    name: aptitude

...
