---
# This role updates the apt packages index and upgrades packages

- name: updating packages
  become: true
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: upgrading packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: true
...
