---
# This role installs the last stable git

- name: adding ppa for the last stable git
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa
    codename: focal #fix "Repo doesn't have a release file" error for linux mint 20.X

- name: installing git
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600      
    name: git
...