---
# This role installs the last stable git

- name: add ppa for the last stable git
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    codename: focal  # fix for "repo doesn't have a release file"

- name: install git
  become: true
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    name: git

...
